# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

City.create(name: 'Dublin', country: 'Ireland')
City.create(name: 'Milan', country: 'Italy')
City.create(name: 'Paris', country: 'France')
City.create(name: 'New York', country: 'United States')
City.create(name: 'Austin', country: 'United States')

Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '1', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '1', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '1', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '2', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '2', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '2', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '2', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '3', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '3', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '3', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '3', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '3', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '4', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '4', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '4', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
Box.create(name: 'Crossfit Avanguardia', url: 'http://www.crossfitireland.ie/', description: 'This is another great description that might be a bit longer.', address: '1411 Vine St.', city_id: '5', country: 'Ireland', facebook: 'https://www.facebook.com/crossfitireland/', instagram: 'https://www.instagram.com/crossfitireland/', is_social: 'TRUE', price: '150', currency: 'EUR', dropin: 'TRUE', certification: 'L3', opening: '2011')
